### Log in with app token
# Authenticates the user and returns an authentication token that can be used in subsequent requests to authenticate the user.
# Use personal login id and app token or use an example user (see above)
# The response includes a token that can be sent in the AuthToken header of subsequent requests to authenticate the user.
# The token is valid for a short time (usually 10 minutes) and can be renewed by sending a request
POST https://mig-smhi.pre.diva-portal.org/login/rest/apptoken
Content-Type: application/vnd.cora.login
Accept: application/vnd.cora.authentication+json

demo@smhi.se
YOUR_APP_TOKEN


### Create a publication

POST https://mig-smhi.pre.diva-portal.org/rest/record/diva-output
Content-Type: application/vnd.cora.recordgroup+xml
Accept: application/vnd.cora.record+xml
AuthToken: YOUR_AUTH_TOKEN

<?xml version="1.0" encoding="UTF-8"?>
<output>
    <recordInfo>
        <validationType>
            <linkedRecordType>validationType</linkedRecordType>
            <linkedRecordId>publication_report</linkedRecordId>
        </validationType>
    <dataDivider>
        <linkedRecordType>system</linkedRecordType>
        <linkedRecordId>divaData</linkedRecordId>
    </dataDivider>
    <permissionUnit>
        <linkedRecordType>permissionUnit</linkedRecordType>
        <linkedRecordId>smhi</linkedRecordId>
    </permissionUnit>
    <visibility>published</visibility>
    </recordInfo>
    <dataQuality>2026</dataQuality>
    <genre type="outputType">publication_report</genre>
    <language repeatId="0">
        <languageTerm type="code" authority="iso639-2b">swe</languageTerm>
    </language>
    <genre type="contentType">pop</genre>
    <titleInfo lang="swe">
        <title>En testpost skapad med API</title>
    </titleInfo>
    <name type="personal" repeatId="0">
        <namePart type="given">Test</namePart>
        <namePart type="family">Testsson</namePart>
        <nameIdentifier type="localId">test</nameIdentifier>
        <role repeatId="0">
            <roleTerm>aut</roleTerm>
        </role>
        <affiliation repeatId="0">
            <namePart>Testuniversitetet</namePart>
            <country>se</country>
        </affiliation>
    </name>
    <abstract lang="swe" repeatId="0">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis purus nunc, feugiat quis nulla et, tincidunt pulvinar nulla. Phasellus urna massa, tempor a nulla ac, tincidunt maximus felis. Cras commodo neque dignissim vulputate varius. Duis purus tortor, faucibus sed velit nec, vestibulum accumsan augue. Praesent placerat eget tellus eget placerat. Mauris id metus eu quam iaculis rhoncus ac nec elit. Suspendisse nec tellus vehicula, facilisis libero nec, placerat lorem. Sed tincidunt, ante et semper faucibus, quam magna commodo magna, in fringilla nibh purus non est. In porttitor magna a nunc aliquam pulvinar a interdum libero. Interdum et malesuada fames ac ante ipsum primis in faucibus. Nunc mollis nulla a scelerisque aliquam. Morbi nec viverra erat. Phasellus blandit, nisl vitae convallis aliquet, justo lorem congue mauris, eu tincidunt sem eros id velit. Donec ut nulla id sem ultrices lobortis.</abstract>
    <originInfo>
        <dateIssued>
            <year>2026</year>
        </dateIssued>
        <name type="corporate" otherType="publisher" repeatId="0">
            <namePart type="publisher">Testförlaget</namePart>
            <place>
                <placeTerm>Stockholm</placeTerm>
            </place>
            <role>
                <roleTerm>pbl</roleTerm>
            </role>
        </name>
    </originInfo>
    <classification authority="ssif" repeatId="0">1</classification>
    <identifier type="isbn" displayLabel="print" repeatId="0">3880531013</identifier>
</output>


### Create a binary record
POST https://mig-smhi.pre.diva-portal.org/rest/record/binary
Content-Type: application/vnd.cora.recordgroup+xml
Accept: application/vnd.cora.record+xml
AuthToken: YOUR_AUTH_TOKEN

<?xml version="1.0" encoding="UTF-8"?>
<binary type="generic">
    <recordInfo>
        <validationType>
            <linkedRecordType>validationType</linkedRecordType>
            <linkedRecordId>genericBinary</linkedRecordId>
        </validationType>
        <dataDivider>
            <linkedRecordType>system</linkedRecordType>
            <linkedRecordId>divaData</linkedRecordId>
        </dataDivider>
        <visibility>published</visibility>
        <hostRecord>
            <linkedRecordType>diva-output</linkedRecordType>
            <linkedRecordId>5159</linkedRecordId>
        </hostRecord>
    </recordInfo>
    <originalFileName>FULLTEXT.pdf</originalFileName>
    <expectedFileSize>5853608</expectedFileSize>
    <expectedChecksum>fdc70efd6e8bc84415df735b33f5ab53794743785c001fe66dd711ac711d1f6ecaa71ef703fd8acdf4ebbcc7c973acfd3e1a9a72b050bfa5faf971231a5288fb</expectedChecksum>
</binary>

### Upload binary file
POST https://mig-smhi.pre.diva-portal.org/rest/record/binary/binary:10558586117406505/master
AuthToken: 8eb2bd4e-cbcf-437e-bd3d-a525be35aa7f
Content-Type: multipart/form-data; boundary=UploadBoundary

--UploadBoundary
Content-Disposition: form-data; name="file"; filename="FULLTEXT.pdf"
Content-Type: application/pdf

< ./data/FULLTEXT.pdf
--UploadBoundary--