### Get example users
# This request fetchches info about the system.On test environments like preview, it includes a list of example users
# that can be used to log in and test the API.
GET https://preview.diva.cora.epc.ub.uu.se/rest/
Accept: application/vnd.cora.deploymentInfo+json


### Log in with app token
# Authenticates the user and returns an authentication token that can be used in subsequent requests to authenticate the user.
# Use personal login id and app token or use an example user (see above)
# The response includes a token that can be sent in the AuthToken header of subsequent requests to authenticate the user.
# The token is valid for a short time (usually 10 minutes) and can be renewed by sending a request
POST https://preview.diva.cora.epc.ub.uu.se/login/rest/apptoken
Content-Type: application/vnd.cora.login
Accept: application/vnd.cora.authentication+json

divaAdmin@cora.epc.ub.uu.se
5e197392-f1d7-49a4-89ad-80431adf4e87

### Renew token
# If the token is expired, you can renew it by sending a request to the renew endpoint
# Use the renew URL from the action link in the login/renew response
POST https://preview.diva.cora.epc.ub.uu.se/login/rest/authToken/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
Accept: application/vnd.cora.authentication+json
Authtoken: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx





<?xml version="1.0" encoding="UTF-8"?>
<output>
	<recordInfo>
		<validationType>
			<linkedRecordType>validationType</linkedRecordType>
			<linkedRecordId>artistic-work_artistic-thesis</linkedRecordId>
		</validationType>
		<dataDivider>
			<linkedRecordType>system</linkedRecordType>
			<linkedRecordId>divaData</linkedRecordId>
		</dataDivider>
		<permissionUnit>
			<linkedRecordType>permissionUnit</linkedRecordType>
			<linkedRecordId>diva</linkedRecordId>
		</permissionUnit>
		<visibility>published</visibility>
	</recordInfo>
    <dataQuality>2026</dataQuality>
	<genre type="outputType">artistic-work_artistic-thesis</genre>
	<language repeatId="0">
		<languageTerm authority="iso639-2b" type="code">ger</languageTerm>
	</language>
    <artisticWork type="outputType">true</artisticWork>
    <genre type="contentType">vet</genre>
    <titleInfo lang="ger">
        <title>TestTitle</title>
        <subtitle>TestSubtitle</subtitle>
    </titleInfo>
    <titleInfo type="alternative" lang="swe" repeatId="0">
        <title>Svensk titel</title>
        <subtitle>Svensk undertitel</subtitle>
    </titleInfo>
	<originInfo>
		<dateIssued>
			<year>2025</year>
		</dateIssued>
	</originInfo>
	<classification authority="ssif" repeatId="0">1</classification>
</output>
